import {StyleSheet} from 'react-native';
import { COLORS, FONTS, SIZES, ComIcons, DelIcons,NavIcons} from '../../../assets/index';

const styles = StyleSheet.create({
    screen: {
      backgroundColor: COLORS.white,
    alignItems:'center',
     flex:1,
    },
    icon2: {
      width: 6,
      height: 4,
      marginTop: 6,
      marginLeft: -2.5,
    },
    icon1: {
      width: 6,
      height: 4,
      marginTop: 6,
      marginLeft: 3,
    },
    foodPrice: {
      textAlign: 'left',
      marginTop: 8,
      fontSize: SIZES.h,
      color: COLORS.darkGrey,
      // fontFamily: FONTS.normal,
      fontStyle: 'normal',
      fontWeight: SIZES.w5,
    },
    classification: {
      textAlign: 'left',
      marginTop: 5,
      fontSize: SIZES.h,
      color: COLORS.darkGrey,
      // fontFamily: FONTS.normal,
      fontStyle: 'normal',
      fontWeight: SIZES.w5,
    },
    foodName: {
      textAlign: 'left',
      fontSize: SIZES.h2,
      color: COLORS.black,
      fontFamily: FONTS.normal,
      fontWeight: SIZES.w5,
    },
    totalPrice: {
      textAlign: 'right',
      marginTop: 26,
      marginRight: 5,
      fontSize: SIZES.h1,
      color: COLORS.red,
      // fontFamily: FONTS.normal,
      fontStyle: 'normal',
      fontWeight: SIZES.w7,
    },
    editTheMeal: {
      flexDirection: 'row',
      textAlign: 'right',
      fontSize: SIZES.h,
      color: COLORS.titleBlack,
      // fontFamily: FONTS.normal,
      fontStyle: 'normal',
      fontWeight: SIZES.w5,
    },
    buttonStyleRed: {
      backgroundColor: COLORS.red,
      height: 30,
      width: 75,
      alignItems: 'center',
      borderRadius: SIZES.r,
      color: COLORS.white,
      alignSelf: 'center',
      fontSize: SIZES.h,
      justifyContent: 'center',
      fontFamily: FONTS.normal,
      fontWeight: 'bold',
    },
    text_color: {
      color: COLORS.white,
      fontWeight: 'bold',
      fontSize: SIZES.h,
      fontFamily: FONTS.normal,
    },
    image: {
      resizeMode: 'contain',
      justifyContent: 'center',
      alignSelf: 'center',
    },
    flatlistView: {
      marginTop: 20,
    },
    note: {
      textAlign: 'left',
      marginTop: 16,
      marginLeft: 15,
      fontWeight: SIZES.w5,
      fontSize: SIZES.h,
      color: COLORS.black,
    },
    noteTextField: {
      marginTop: 16,
      marginRight: 19,
      marginLeft: 15,
      borderRadius: SIZES.r1,
      backgroundColor: '#F2F3F0',
    },
    noteText: {
      textAlign: 'left',
      marginTop: 16,
      marginLeft: 14,
      marginBottom: 16,
    },
    line: {
      marginRight: 17,
      marginLeft: 15,
      backgroundColor: '#F5F5F5',
      height: 1,
    },
    coupon: {
      flex : SIZES.f1,
      textAlign: 'left',
      marginTop: 23,
      marginLeft: 15,
      fontSize: SIZES.h2,
      fontWeight: SIZES.w7,
      fontStyle: 'normal',
      color: COLORS.black,
    },
    codeView: {
      borderRadius: SIZES.r,
      marginTop: 16,
      borderColor: '#F2F3F0',
      borderWidth: 1,
    },
    codeText: {
      fontSize: SIZES.h,
      width: 84,
      marginTop: 8,
      marginLeft: 8,
      marginRight: 8,
      marginBottom: 7,
      textAlign: 'center',
      color: '#A1A1A1',
    },
    applyView: {
      marginTop: 16,
      marginRight: 19,
      marginLeft: 9,
      backgroundColor: '#F2F3F0',
      borderRadius: SIZES.r,
      width: 85,
      height: 31,
    },
    applyText: {
      textAlign: 'center',
      marginTop: 8,
      marginLeft: 25,
      marginRight: 24,
      marginBottom: 7,
      fontSize: SIZES.h,
      color: '#A1A1A1',
    },
    subtotalView: {
      flexDirection: 'row',
      marginTop: 17,
      marginLeft: 15,
      marginRight: 19,
    },
    subtotalText: {
      flex : SIZES.f1,
      textAlign: 'left',
      fontWeight: SIZES.w7,
      fontSize: SIZES.h2,
      fontStyle: 'normal',
      color: COLORS.black,
    },
    subtotalAmount: {
      flex : SIZES.f1,
      textAlign: 'right',
      fontWeight: SIZES.w7,
      fontSize: SIZES.h2,
      fontStyle: 'normal',
      color: COLORS.black,
    },
    deliveryView: {
      flexDirection: 'row',
      marginTop: 23,
      marginLeft: 15,
      marginRight: 19,
    },
  
    deliveryText: {
      flex : SIZES.f1,
      textAlign: 'left',
      fontSize: SIZES.h2,
      fontWeight: SIZES.w7,
      fontStyle: 'normal',
      color: COLORS.black,
    },
  
    deliveryAmount: {
      flex : SIZES.f1,
      textAlign: 'right',
      fontWeight: SIZES.w7,
      fontSize: SIZES.h2,
      fontStyle: 'normal',
      color: COLORS.black,
    },
    totalView: {
      flexDirection: 'row',
      marginTop: 24,
      marginLeft: 15,
      marginRight: 19,
    },
    totalText: {
      flex : SIZES.f1,
      textAlign: 'left',
      fontSize: SIZES.h3,
      fontWeight: SIZES.w7,
      fontStyle: 'normal',
      color: COLORS.black,
    },
    totalAmount: {
      flex : SIZES.f1,
      textAlign: 'right',
      fontWeight: SIZES.w7,
      fontSize: SIZES.h3,
      fontStyle: 'normal',
      color: COLORS.red,
    },
    button1: {
      backgroundColor: 'red',
      height: SIZES.btnHeight ,
      alignItems: 'center',
      borderRadius: SIZES.r1,
      marginTop: 28,
      marginLeft: SIZES.mlr1,
      marginRight: SIZES.mlr1,
      color: COLORS.white,
      justifyContent: 'center',
    },
    buttonText1: {
      fontStyle: 'normal',
      fontWeight: SIZES.w5,
      fontSize: SIZES.h3,
      color: COLORS.white,
    },
  });
    export default styles;