export const FETCH_PLACES = 'FETCH_PLACES';
export const FETCH_PLACES_SUCCESS = 'FETCH_PLACES_SUCCESS';
export const FETCH_PLACES_FAILURE = 'FETCH_PLACES_FAILURE';
export const CLEAR_PLACES_LIST = 'CLEAR_PLACES_LIST';

export const REVERSE_GEO_PLACES = 'REVERSE_GEO_PLACES'
export const REVERSE_GEO_SUCCESS = 'REVERSE_GEO_SUCCESS';
export const REVERSE_GEO_FAILURE = 'REVERSE_GEO_FAILURE';
