export const WONDERPOINTS_LIST_REQUEST = "WONDERPOINTS_LIST_REQUEST";
export const WONDERPOINTS_LIST_REQUEST_SUCCESS = "WONDERPOINTS_LIST_REQUEST_SUCCESS";
export const WONDERPOINTS_LIST_REQUEST_FAILURE = "WONDERPOINTS_LIST_REQUEST_FAILURE";

export const WONDERPOINTS_COUNT_REQUEST = "WONDERPOINTS_COUNT_REQUEST";
export const WONDERPOINTS_COUNT_REQUEST_SUCCESS = "WONDERPOINTS_COUNT_REQUEST_SUCCESS";
export const WONDERPOINTS_COUNT_REQUEST_FAILURE = "WONDERPOINTS_COUNT_REQUEST_FAILURE";
