import {StyleSheet, Dimensions, Platform} from 'react-native';

import {COLORS, FONTS, SIZES, ComIcons, DelIcons, NavIcons} from 'assets/index';

export default StyleSheet.create({
  safeAreaContainer: {
    paddingHorizontal: 24,
    backgroundColor: '#e1342f',
  },
  screen: {
    flex: SIZES.f1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLORS.white,
  },
  BoxShadow: {
    shadowColor: COLORS.black,
    shadowOpacity: 0.25,
    shadowOffset: {width: 0, height: 0},
    shadowRadius: 1,
    elevation: 1,
    borderWidth: 1,
    // overflow: 'hidden',
  },
  shadowForView: {
    borderWidth: 1,
    borderRadius: 8,
    borderColor: '#ddd',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.25,
    shadowRadius: 3,
    elevation: 3,
    backgroundColor: "#FFFFFF",
  }, 
  menuItem: {
    textAlign: 'left',
    fontWeight: SIZES.w7,
    fontSize: SIZES.h2,
    color: COLORS.black,
    fontFamily: FONTS.normal,
    alignSelf: 'flex-start',
    marginBottom: 8,
    lineHeight: SIZES.l2,
  },
  wrapperView: {
    padding: 10,
    marginTop: 5,
  },
  safeAreaContainerLight: {
    backgroundColor: COLORS.white,
    flex: SIZES.f1,
    // fontFamily: FONTS.light,
  },
  MainContainer: {
    backgroundColor: COLORS.background2,
    height: '100%',
  },
  MainContainerLight: {
    // backgroundColor: COLORS.white,
    height: '100%',
    // paddingTop: 20,
  },

  highlight: {
    fontWeight: SIZES.w7,
  },
  row: {
    flex: SIZES.f1,
    flexDirection: 'row',
    paddingTop: 15,
    paddingBottom: 15,
  },
  inputWrap: {
    flex: SIZES.f1,
    borderColor: '#cccccc',
    borderBottomWidth: 1,
    marginBottom: 10,
    flexDirection: 'row',
  },
  inputdate: {
    fontSize: SIZES.h1,
    marginBottom: -12,
  },
  headingText: {
    alignSelf: 'center',
    color: COLORS.white,
    fontFamily: FONTS.normal,
    fontWeight: SIZES.w5,
    fontSize: SIZES.h9,
    // marginTop: 20,
  },
  headingTitle: {
    alignSelf: 'center',
    color: COLORS.titleBlack,
    // fontFamily: FONTS.bold,
    fontSize: SIZES.h6,
  },
  image: {
    marginTop: 111,

    height: 227,
    width: 274,
    alignSelf: 'center',
  },
  sectionTitle: {
    fontSize: SIZES.h3,
    color: COLORS.black,
    fontWeight: SIZES.w7,
    marginTop: 49,
    marginLeft: 90,
    marginRight: 90,
    alignSelf: 'center',
    // width: 223,
  },
  sectionDescription: {
    fontSize: SIZES.h4,
    color: COLORS.black,
    fontWeight: SIZES.w2,
    marginTop: 16,
    marginLeft: 35,
    marginRight: 35,
    alignSelf: 'center',
  },
  bottomText: {
    fontSize: SIZES.h4,
    color: COLORS.titleBlack,
    fontWeight: SIZES.w5,
    marginTop: 16,
    marginLeft: 35,
    marginRight: 35,
    textAlign: 'center',
    fontFamily: FONTS.normal,
  },

  deliveryView: {
    flexDirection: 'row',
    marginTop: 22,
    marginLeft: 105,
    marginRight: 90,
    alignSelf: 'center',
  },

  deliveryTime: {
    fontSize: SIZES.h,
    color: COLORS.black,
    fontWeight: SIZES.w5,
    alignSelf: 'center',
    fontFamily: FONTS.normal,
  },
  button1: {
    backgroundColor: COLORS.red,
    height: SIZES.btnHeight,
    alignItems: 'center',
    borderRadius: SIZES.r1,
    marginTop: 140,
    marginLeft: SIZES.mlr1,
    marginRight: SIZES.mlr1,
    color: COLORS.white,
    justifyContent: 'center',
  },
  buttonText1: {
    fontWeight: SIZES.w5,
    fontSize: SIZES.w5.h3,
    color: COLORS.white,
  },
  button2: {
    marginTop: 27,
    marginLeft: 133,
    marginRight: 134,
    marginBottom: 53,
    justifyContent: 'center',
    alignItems: 'center',
  },
  buttonText2: {
    color: COLORS.black,
    fontWeight: SIZES.w5,
    fontSize: SIZES.h3,
    fontFamily: FONTS.normal,
  },

  headingDesc: {
    color: COLORS.black,
    fontFamily: FONTS.normal,
    fontSize: SIZES.h5,
    fontWeight: SIZES.w5,
    textAlign: 'center',
    justifyContent: 'center',
  },
  headingDescTwo: {
    color: COLORS.black,
    fontFamily: FONTS.normal,
    fontSize: SIZES.h4,
    fontWeight: SIZES.w5,
    textAlign: 'center',
    justifyContent: 'center',
  },
  descText: {
    color: COLORS.black,
    fontFamily: FONTS.light,
    fontSize: SIZES.h2,
    width: '100%',
    alignSelf: 'center',
    textAlign: 'center',
    justifyContent: 'center',
    lineHeight: SIZES.l3,
  },
  descHistoryText: {
    color: COLORS.black,
    fontFamily: FONTS.light,
    fontSize: SIZES.h1,
    textAlign: 'left',
    justifyContent: 'center',
    lineHeight: SIZES.l3,
  },
  descTextLight: {
    color: COLORS.black,
    fontFamily: FONTS.light,
    fontSize: SIZES.h2,
    width: '100%',
    alignSelf: 'center',
    textAlign: 'center',
    justifyContent: 'center',
  },

  buttonStyle: {
    borderWidth: 1,
    borderColor: COLORS.white,
    backgroundColor: COLORS.background2,
    borderRadius: SIZES.r1,
    height: SIZES.btnHeight,
    alignItems: 'center',
    justifyContent: 'center',
    // width: '90%',
    marginTop: 30,
  },
  container: {
    flex: SIZES.f1,
    marginTop: 0,
  },
  item: {
    backgroundColor: '#f9c2ff',
    padding: 20,
    marginVertical: 8,
    marginHorizontal: 16,
  },
  title: {
    fontSize: SIZES.h9,
  },

  mainBody: {
    flex: SIZES.f1,
    backgroundColor: COLORS.white,
    margin: 0
  },
  mapStyle: {
    position: 'relative',
  },

  addressButtonView: {
    width: '100%',
  },
  SectionStyle: {
    flexDirection: 'row',
    marginTop: 38,
    margin: 8,
  },
  ErrorTextStyle: {
    marginTop: 10,
    margin: 8,
    color: COLORS.red,
    fontFamily: FONTS.light,
    fontSize: SIZES.h1,
    fontWeight: 'bold',
  },
  AddAddressStyle: {
    marginTop: 38,
  },
  SearchStyle: {
    flexDirection: 'row',
    backgroundColor: COLORS.white,
    height: 20,
    margin: 8,
  },
  ChooseType: {
    flexDirection: 'row',
    marginTop: 8,
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },

  buttonGrayStyle: {
    backgroundColor: COLORS.white,
    height: 45,
    alignItems: 'center',
    borderRadius: SIZES.r1,
    borderColor: COLORS.grey,
    borderWidth: 1,
    marginLeft: 15,
    marginRight: 15,
    color: COLORS.titleBlack,
    marginTop: 40,
    marginBottom: -25,
    justifyContent: 'center',
  },
  buttonTextStyle: {
    color: COLORS.white,
    fontSize: SIZES.h2,
    fontWeight: SIZES.w5,
    // fontFamily: FONTS.bold,
    marginLeft:16,
    marginRight:16,
  },
  buttonTextGratStyle: {
    color: COLORS.titleBlack,
    fontSize: SIZES.h2,
    // fontFamily: FONTS.bold,
  },

  inputStyle: {
    borderBottomWidth: Platform.OS === 'android' ? 0 : 1,
    borderBottomColor: '#EFEFEF',
    fontSize: SIZES.h2,
    flex: 1,
    color: COLORS.black,
    fontFamily: FONTS.light,
    lineHeight: SIZES.l3,
    marginLeft: 6,
    marginRight: 6,
  },

  searchField: {
    flex: SIZES.f1,
    borderBottomWidth: 0,
    height: Platform.OS === 'android' ? 40 : 20,
    color: '#A2A2A2',
    lineHeight: SIZES.l2,
    fontSize: SIZES.h1,
    fontFamily: FONTS.normal,
    fontWeight: SIZES.w2,
  },
  inputPhone: {
    fontFamily: FONTS.normal,
    fontSize: SIZES.h1,
    fontWeight: SIZES.w5,
    marginLeft: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  otpTextBox: {
    flex: SIZES.f1,
    color: COLORS.black,
    paddingLeft: 15,
    paddingRight: 15,
    borderWidth: 1,
    borderRadius: SIZES.r,
    borderColor: COLORS.red,
    fontSize: SIZES.h2,
    height: 50,
    width: 50,
    fontFamily: FONTS.light,
    margin: 10,
    textAlign: 'center',
  },
  FollowBox: {
    marginRight: 10,
    marginLeft:10,
    marginBottom:10,
    resizeMode: 'contain',
  },
  sectionThree: {
    color: COLORS.black,
    margin: 10,
    padding: 20,
    justifyContent: 'center',
  },
  OTPTextField: {
    color: COLORS.black,
    margin: 10,
    padding: 20,
    justifyContent: 'center',
    borderColor: COLORS.grey,
    borderWidth: 1,
  },
  registerTextStyle: {
    color: COLORS.black,
    textAlign: 'center',
    fontWeight: SIZES.w5,
    fontFamily: FONTS.light,
    fontSize: SIZES.h,
    alignSelf: 'center',
    justifyContent: 'center',
    padding: 3,
  },
  registerTextStyleRed: {
    marginTop: Platform.OS === 'android' ? 10 : 0,
    color: COLORS.red,
  },
  headerTitle: {
    color: COLORS.black,
    fontFamily: FONTS.normal,
    fontSize: SIZES.h3,
    fontWeight: SIZES.w5,
    lineHeight: SIZES.l3,
  },
  navBackButton: {
    width: 12,
    height: 21,
    marginLeft: SIZES.mlr1,
    resizeMode: 'contain',
  },
  navCrossButton: {
    width: 25,
    height: 25,
    marginLeft: SIZES.mlr1,
    resizeMode: 'contain',
  },
  textTitle: {
    fontWeight: SIZES.w7,
    color: COLORS.black,
    fontFamily: FONTS.normal,
    fontSize: SIZES.h3,
    alignSelf: 'flex-start',
    textAlign: 'center',
    justifyContent: 'center',
    margin: 10,
    marginTop: 20,
    lineHeight: SIZES.l4,
  },
  itemTitle: {
    fontSize: SIZES.h,
    color: COLORS.black,
    fontFamily: FONTS.normal,
    alignSelf: 'center',
    textAlign: 'center',
    justifyContent: 'center',
    height: 50,
  },
  prodDescText: {
    color: COLORS.black,
    marginLeft: 10,
    marginRight: 10,
    fontSize: SIZES.h1,
    fontFamily: FONTS.normal,
  },
  prodDescTextLight: {
    color: COLORS.black,
    fontSize: SIZES.h1,
    fontFamily: FONTS.light,
  },
  rateText: {
    color: COLORS.black,
    fontSize: SIZES.h3,
    fontFamily: FONTS.normal,
    fontWeight: SIZES.w5,
  },
  centerTextStyle: {
    color: COLORS.black,
    textAlign: 'center',
    fontSize: SIZES.h2,
    fontFamily: FONTS.normal,
    fontWeight: SIZES.w5,
    lineHeight: SIZES.l3,
  },
  CategoryView: {
    justifyContent: 'center',
    alignItems: 'center',
    flex: SIZES.f1,
    height: 180,
    width: 150,
    marginTop: 20,
    marginRight: 20,
    borderWidth: 1,
    borderColor: COLORS.background,
    borderRadius: SIZES.r1,
  },
  // New Added Css
  aboutPageTitle: {
    color: COLORS.black,
    fontFamily: FONTS.normal,
    fontSize: SIZES.h,
    fontWeight: SIZES.w7,
    textAlign: 'left',
  },
  aboutPageDesc: {
    color: COLORS.black,
    fontFamily: FONTS.normal,
    fontSize: SIZES.h,
    alignSelf: 'center',
    textAlign: 'left',
    justifyContent: 'center',
    marginTop: 12,
    marginBottom: 12,
  },
});
