export const FETCH_CATEGORY_REQUEST = 'FETCH_CATEGORY_REQUEST';
export const FETCH_CATEGORY_REQUEST_SUCCESS = 'FETCH_CATEGORY_REQUEST_SUCCESS';
export const FETCH_CATEGORY_REQUEST_FAILURE = 'FETCH_CATEGORY_REQUEST_FAILURE';
export const FETCH_BANNER_REQUEST = 'FETCH_BANNER_REQUEST';
export const BANNER_REQUEST_SUCCESS = 'BANNER_REQUEST_SUCCESS';
export const BANNER_REQUEST_FAILURE = 'BANNER_REQUEST_FAILURE';
