export const SET_CHECKOUT_REQUEST = "SET_CHECKOUT_REQUEST";
export const SET_CHECKOUT_REQUEST_SUCCESS = "SET_CHECKOUT_REQUEST_SUCCESS";
export const SET_CHECKOUT_REQUEST_FAILURE  = "SET_CHECKOUT_REQUEST_FAILURE";