export const SHOW_PRODUCT_REQUEST = 'SHOW_PRODUCT_REQUEST';
export const SHOW_PRODUCT_REQUEST_SUCCESS = 'SHOW_PRODUCT_REQUEST_SUCCESS';
export const SHOW_PRODUCT_REQUEST_FAILURE = 'SHOW_PRODUCT_REQUEST_FAILURE';
