export const SUBMIT_OTP_REQUEST = 'SUBMIT_OTP_REQUEST';
export const SUBMIT_OTP_REQUEST_SUCCESS = 'SUBMIT_OTP_REQUEST_SUCCESS';
export const SUBMIT_OTP_REQUEST_FAILURE = 'SUBMIT_OTP_REQUEST_FAILURE';

export const RESEND_OTP_REQUEST = 'RESEND_OTP_REQUEST';
export const RESEND_OTP_REQUEST_SUCCESS = 'RESEND_OTP_REQUEST_SUCCESS';
export const RESEND_OTP_REQUEST_FAILURE = 'RESEND_OTP_REQUEST_FAILURE';