export const GET_ADDRESS_REQUEST  = 'GET_ADDRESS_REQUEST';
export const GET_ADDRESS_REQUEST_SUCCESS = 'GET_ADDRESS_REQUEST_SUCCESS' 
export const GET_ADDRESS_REQUEST_FAILURE = 'GET_ADDRESS_REQUEST_FAILURE';
