export const DELETE_ADDRESS_REQUEST = 'DELETE_ADDRESS_REQUEST';
export const DELETE_ADDRESS_REQUEST_SUCCESS = 'DELETE_ADDRESS_REQUEST_SUCCESS';
export const DELETE_ADDRESS_REQUEST_FAILURE = 'DELETE_ADDRESS_REQUEST_FAILURE';
