export const GET_INGREDIENTS_REQUEST = 'GET_INGREDIENTS_REQUEST';
export const GET_INGREDIENTS_REQUEST_SUCCESS = 'GET_INGREDIENTS_REQUEST_SUCCESS'
export const GET_INGREDIENTS_REQUEST_FAILURE = 'GET_INGREDIENTS_REQUEST_FAILURE';
