export const FETCH_CUISINES_REQUEST = "FETCH_CUISINES_REQUEST";
export const FETCH_CUISINES_REQUEST_SUCCESS = "FETCH_CUISINES_REQUEST_SUCCESS";
export const FETCH_CUISINES_REQUEST_FAILURE = "FETCH_CUISINES_REQUEST_FAILURE";