import {StyleSheet} from 'react-native';
import {
  COLORS,
  FONTS,
  SIZES,
  ComIcons,
  DelIcons,
  NavIcons,
} from '../../../assets/index';

const styles = StyleSheet.create({
  box: {
    marginLeft: SIZES.mlr1,
    marginRight: SIZES.mlr1,
    marginTop: 40,
    height: 315,
    shadowColor: COLORS.titleBlack,
    shadowOffset: {width: 1, height: 1},
    shadowOpacity: 0.15,
    shadowRadius: 2,
    // overflow: 'hidden',
    borderColor: '#dddddd',
    borderRadius: SIZES.r1,
    borderWidth: 1,
  },
  text1: {
    marginTop: 28,
    fontSize: SIZES.h3,
    fontFamily: FONTS.normal,
    fontWeight: SIZES.w5,
    color: COLORS.black,
    lineHeight: SIZES.l5,
    letterSpacing: 0.03,
    textAlign: 'center',
    marginLeft: 30,
    marginRight: 30,
  },
  text2: {
    marginTop: 10,
    fontSize: SIZES.h,
    fontFamily: FONTS.normal,
    fontWeight: SIZES.w5,
    color: COLORS.black,
    alignSelf: 'center',
    lineHeight: SIZES.l5,
    textAlign: 'center',
    marginLeft: 35,
    marginRight: 35,
  },
  text3: {
    marginTop: 43,
    fontSize: SIZES.h3,
    fontFamily: FONTS.normal,
    fontWeight: SIZES.w5,
    color: COLORS.black,
    lineHeight: SIZES.l4,
    letterSpacing: 0.03,
    textAlign: 'center',
  },
  text4: {
    marginTop: 10,
    marginBottom: 26,
    fontSize: SIZES.h1,
    fontFamily: FONTS.normal,
    fontWeight: SIZES.w5,
    color: COLORS.black,
    lineHeight: SIZES.l2,
    letterSpacing: 0.03,
    textAlign: 'center',
  },
  messageBox: {
    flexDirection: 'row',
    borderWidth: 1,
    bottom: 0,
    height: 80,
    borderTopColor: COLORS.grey,
    borderColor: 'white',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  messageText: {
    fontSize: SIZES.h2,
    fontFamily: FONTS.normal,
    fontWeight: SIZES.w4,
    color: '#898989',
    marginLeft: SIZES.mlr1,
    marginRight: SIZES.mlr1,
    alignSelf: 'center',
  },
  buttonView: {
    marginRight: 15,
  },
  buttonText: {
    fontSize: SIZES.h3,
    fontFamily: FONTS.normal,
    fontWeight: SIZES.w7,
    color: '#898989',
    alignSelf: 'center',
    lineHeight: SIZES.l6,
  },
});
export default styles;
