export const GET_WISHLIST_REQUEST = 'GET_WISHLIST_REQUEST';
export const GET_WISHLIST_REQUEST_SUCCESS = 'GET_WISHLIST_REQUEST_SUCCESS';
export const GET_WISHLIST_REQUEST_FAILURE = 'GET_WISHLIST_REQUEST_FAILURE';

export const DELETE_WISHLIST_REQUEST = "DELETE_WISHLIST_REQUEST";
export const DELETE_WISHLIST_REQUEST_SUCCESS = "DELETE_WISHLIST_REQUEST_SUCCESS";
export const DELETE_WISHLIST_REQUEST_FAILURE = "DELETE_WISHLIST_REQUEST_FAILURE";

export const DELETE_WISHLIST_ITEM_REQUEST = "DELETE_WISHLIST_ITEM_REQUEST";
export const DELETE_WISHLIST_ITEM_REQUEST_SUCCESS = "DELETE_WISHLIST_ITEM_REQUEST_SUCCESS";
export const DELETE_WISHLIST_ITEM_REQUEST_FAILURE = "DELETE_WISHLIST_ITEM_REQUEST_FAILURE";

export const ADD_TO_CART_WISHLIST_REQUEST = "ADD_TO_CART_WISHLIST_REQUEST"
export const ADD_TO_CART_WISHLIST_REQUEST_SUCCESS = "ADD_TO_CART_WISHLIST_REQUEST_SUCCESS"
export const ADD_TO_CART_WISHLIST_REQUEST_FAILURE = "ADD_TO_CART_WISHLIST_REQUEST_FAILURE"
