import {StyleSheet} from 'react-native';
import {
  COLORS,
  FONTS,
  SIZES,
  ComIcons,
  DelIcons,
  NavIcons,
} from '../../../assets/index';

const styles = StyleSheet.create({
  imageWish: {
    marginTop: 100,
    height: 222,
    width: 222,
    alignSelf: 'center',
  },
  cellStyle: {
    flexDirection: 'row',
    borderWidth: 1,
    borderColor: '#F2F3F0',
    borderRadius: SIZES.r1,
    height: 110,
    marginLeft: 15,
    marginRight: 15,
    marginBottom: 15,
    shadowColor: 'black',
    shadowOpacity: 0.12,
    shadowOffset: { width: 0, height: 0 },
    shadowRadius: 2,
  },
  swipeView: { justifyContent: 'center', marginRight: 10, width: 100, borderColor: '#dddddd', borderWidth: 1 },
  buttonStyleRed: {
    backgroundColor: COLORS.red,
    height: 29,
    width: 100,
    borderRadius: SIZES.r,
    marginBottom: 8,
    // marginTop: 8,
    alignItems: 'center',
    color: COLORS.white,
    alignSelf: 'center',
    fontSize: SIZES.h,
    justifyContent: 'center',
    fontFamily: FONTS.normal,
    fontWeight: 'bold',
  },
  text_color: {
    color: COLORS.white,
    fontSize: SIZES.h,
    fontWeight: SIZES.w5,
    fontFamily: FONTS.normal,
  },
  sectionTitle: {
    fontSize: SIZES.h7,
    color: COLORS.black,
    fontWeight: SIZES.w7,
    // marginTop: 10,
    // marginBottom: 10,
    marginLeft: 20,
    marginRight: 20,
    alignSelf: 'center',
    fontFamily: FONTS.normal,
  },
  icon2: {
    width: 6,
    height: 4,
    marginTop: 6,
    marginLeft: -2.5,
  },
  icon1: {
    width: 6,
    height: 4,
    marginTop: 6,
    marginLeft: 3,
  },
  foodPrice: {
    textAlign: 'left',
    marginTop: 5,
    fontSize: SIZES.h1,
    color: COLORS.darkGrey,
    // fontFamily: FONTS.normal,
    fontStyle: 'normal',
    fontWeight: SIZES.w5,
  },
  classification: {
    textAlign: 'left',
    marginTop: 5,
    marginBottom: 10,
    fontSize: SIZES.h,
    color: COLORS.black,
    fontFamily: FONTS.light,
    textAlign: 'left',

  },
  foodName: {
    textAlign: 'left',
    fontSize: SIZES.h1,
    marginTop: 3,
    color: COLORS.black,
    fontFamily: FONTS.normal,
    fontWeight: SIZES.w5,
  },
  totalPrice: {
    textAlign: 'right',
    marginTop: 3,
    marginRight: 5,
    fontSize: SIZES.h1,
    color: COLORS.red,
    fontFamily: FONTS.normal,
    fontWeight: SIZES.w7,
  },
  editTheMeal: {
    flexDirection: 'row',
    textAlign: 'right',
    fontSize: SIZES.h,
    color: COLORS.black,
    fontFamily: FONTS.normal,
    fontWeight: SIZES.w5,
  },
  image: {
    width: 97,
    height: '100%',
    backgroundColor: '#F2F3F0',
    borderRadius: SIZES.r1,
  },
  flatlistView: {
    marginTop: 20,
  },
  note: {
    textAlign: 'left',
    marginTop: 16,
    marginLeft: 15,
    fontWeight: SIZES.w5,
    fontSize: SIZES.h,
    color: COLORS.black,
    fontFamily: FONTS.normal,
  },
  noteTextField: {
    marginTop: 16,
    marginRight: 19,
    marginLeft: 15,
    borderRadius: SIZES.r1,
    fontSize: SIZES.h,
    color: '#A2A2A2',
    fontFamily: FONTS.normal,
  },
  noteText: {
    textAlign: 'left',
    marginTop: 16,
    marginLeft: 14,
    marginBottom: 16,
  },
  line: {
    marginRight: 17,
    marginLeft: 15,
    backgroundColor: '#F5F5F5',
    height: 1,
  },
  coupon: {
    flex: SIZES.f1,
    textAlign: 'left',
    marginTop: 23,
    marginLeft: 15,
    fontSize: SIZES.h2,
    fontWeight: SIZES.w5,
    fontFamily: FONTS.normal,
    color: COLORS.black,
  },
  sectionDescription: {
    fontSize: SIZES.h5,
    color: COLORS.black,
    fontWeight: SIZES.w2,
    marginTop: 16,
    marginLeft: 35,
    marginRight: 35,
    fontFamily: FONTS.normal,
    alignSelf: 'center',
  },
  screen: {
    flex: SIZES.f1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLORS.white,
    width: '100%',
  },
  deliveryView: {
    flexDirection: 'row',
    marginTop: 22,
    marginLeft: 105,
    marginRight: 90,
    alignSelf: 'center',
  },

  deliveryTime: {
    fontSize: SIZES.h,
    color: COLORS.black,
    fontWeight: SIZES.w4,
    alignSelf: 'center',
  },
  button1: {
    backgroundColor: 'red',
    height: 45,
    width: 150,
    alignItems: 'center',
    borderRadius: SIZES.r1,
    marginTop: 30,
    marginBottom: 170,
    marginLeft: SIZES.mlr1,
    marginRight: SIZES.mlr1,
    color: COLORS.white,
    justifyContent: 'center',
  },
  buttonText1: {
    fontFamily: FONTS.normal,
    fontWeight: SIZES.w5,
    fontSize: SIZES.h3,
    color: COLORS.white,
  },
  button2: {
    marginTop: 27,
    marginLeft: 133,
    marginRight: 134,
    marginBottom: 53,
    justifyContent: 'center',
    alignItems: 'center',
  },
  buttonText2: {
    color: COLORS.black,
    fontStyle: 'normal',
    fontWeight: SIZES.w5,
    fontSize: SIZES.h3,
  },
});
export default styles;
