export const GET_UPCOMING_ORDERS_REQUEST = 'GET_UPCOMING_ORDERS_REQUEST';
export const GET_UPCOMING_ORDERS_REQUEST_SUCCESS = 'GET_UPCOMING_ORDERS_REQUEST_SUCCESS';
export const GET_UPCOMING_ORDERS_REQUEST_FAILURE = 'GET_UPCOMING_ORDERS_REQUEST_FAILURE';
