export const GET_NOTIFICATIONS_REQUEST = "GET_NOTIFICATIONS_REQUEST";
export const GET_NOTIFICATIONS_REQUEST_SUCCESS = "GET_NOTIFICATIONS_REQUEST_SUCCESS";
export const GET_NOTIFICATIONS_REQUEST_FAILURE  = "GET_NOTIFICATIONS_REQUEST_FAILURE";