export const FETCH_CATEGORY_PRODUCT_REQUEST = 'FETCH_CATEGORY_PRODUCT_REQUEST';
export const CATEGORY_PRODUCT_REQUEST_SUCCESS = 'CATEGORY_PRODUCT_REQUEST_SUCCESS';
export const CATEGORY_PRODUCT_REQUEST_FAILURE = 'CATEGORY_PRODUCT_REQUEST_FAILURE';


export const ADD_TO_CART_REQUEST = 'ADD_TO_CART_REQUEST'; 
export const ADD_TO_CART_REQUEST_SUCCESS = 'ADD_TO_CART_REQUEST_SUCCESS'; 
export const ADD_TO_CART_REQUEST_FAILURE = 'ADD_TO_CART_REQUEST_FAILURE'; 

export const ADD_TO_WISHLIST_REQUEST = 'ADD_TO_WISHLIST_REQUEST';
export const ADD_TO_WISHLIST_REQUEST_SUCCESS = 'ADD_TO_WISHLIST_REQUEST_SUCCESS';
export const ADD_TO_WISHLIST_REQUEST_FAILURE = 'ADD_TO_WISHLIST_REQUEST_FAILURE'; 
