export const CART_LIST_REQUEST = 'CART_LIST_REQUEST';
export const CART_LIST_REQUEST_SUCCESS = 'CART_LIST_REQUEST_SUCCESS';
export const CART_LIST_REQUEST_FAILURE = 'CART_LIST_REQUEST_FAILURE';

export const SET_CART_REQUEST = "SET_CART_REQUEST";
export const SET_CART_REQUEST_SUCCESS = "SET_CART_REQUEST_SUCCESS";
export const SET_CART_REQUEST_FAILURE = "SET_CART_REQUEST-FAILURE";

export const DELETE_ITEM_REQUEST = 'DELETE_ITEM_REQUEST';
export const DELETE_ITEM_REQUEST_SUCCESS = 'DELETE_ITEM_REQUEST_SUCCESS';
export const DELETE_ITEM_REQUEST_FAILURE = 'DELETE_ITEM_REQUEST_FAILURE';

export const APPLY_COUPON_REQUEST = 'APPLY_COUPON_REQUEST';
export const APPLY_COUPON_REQUEST_SUCCESS = 'APPLY_COUPON_REQUEST_SUCCESS';
export const APPLY_COUPON_REQUEST_FAILURE = 'APPLY_COUPON_REQUEST_FAILURE';
export const RESET_COUPON_DATA = 'RESET_COUPON_DATA'
