import {StyleSheet} from 'react-native';
import {COLORS, FONTS, SIZES, ComIcons, DelIcons, NavIcons} from 'assets/index';

const styles = StyleSheet.create({
  noteTextField: {
    marginTop: 16,
    borderRadius: SIZES.r1,
    fontSize: SIZES.h,
    color: COLORS.black,
    fontFamily: FONTS.normal,
    borderWidth: 1,
    borderColor: '#dddddd',
    lineHeight: SIZES.l3,
  },
  noteText: {
    textAlign: 'left',
    marginTop: 16,
    marginLeft: 14,
    marginBottom: 16,
    fontSize: SIZES.h,
    color: '#000000',
    fontFamily: FONTS.normal,
    fontWeight: SIZES.w3,
    lineHeight: SIZES.l2,
  },
  line: {
    backgroundColor: '#F5F5F5',
    height: 1,
  },
  coupon: {
    flex: SIZES.f1,
    textAlign: 'left',
    marginTop: 20,
    fontSize: SIZES.h2,
    fontWeight: SIZES.w5,
    fontFamily: FONTS.normal,
    color: COLORS.black,
  },
  codeView: {
    borderRadius: SIZES.r,
    marginTop: 16,
    borderColor: '#F2F3F0',
    height: 32,
    borderWidth: 1,
  },
  codeText: {
    fontSize: SIZES.h,
    width: 84,
    marginTop: 8,
    marginLeft: 8,
    marginRight: 8,
    marginBottom: 7,
    textAlign: 'center',
    color: COLORS.black,
    fontFamily: FONTS.normal,
  },
  coinText: {
    fontSize: SIZES.h,
    textAlign: 'center',
    color: COLORS.black,
    fontFamily: FONTS.normal,
  },
  applyView: {
    marginTop: 16,
    marginLeft: 9,
    backgroundColor: COLORS.red,
    fontWeight: SIZES.w5,
    borderRadius: SIZES.r,
    width: 85,
    height: 31,
    fontFamily: FONTS.normal,
  },
  applyText: {
    textAlign: 'center',
    marginTop: 8,
    marginBottom: 7,
    fontSize: SIZES.h,
    fontWeight: SIZES.w5,
    color: COLORS.white,
    fontFamily: FONTS.normal,
  },
  subtotalView: {
    flexDirection: 'row',
    flex: SIZES.f1,
    marginTop: 17,
    justifyContent: 'space-between',
  },
  subtotalText: {
    flex: 1 / 2,
    textAlign: 'left',
    fontWeight: SIZES.w5,
    fontSize: SIZES.h2,
    fontFamily: FONTS.normal,
    color: COLORS.black,
  },
  deliveryView: {
    flexDirection: 'row',
    marginTop: 23,
    marginBottom:10,
  },
  totalView: {
    flex:1,
    flexDirection: 'row',
    marginTop: 13,
    marginBottom:13,
    justifyContent:'space-between',
  },
  totalAmount: {
    textAlign: 'left',
    fontWeight: 'bold',
    fontSize: SIZES.h3,
    fontStyle: 'normal',
    color: COLORS.red,
  },
});

export default styles;
