export const ADD_ADDRESS_REQUEST = 'ADD_ADDRESS_REQUEST';
export const ADD_ADDRESS_REQUEST_SUCCESS = 'ADD_ADDRESS_REQUEST_SUCCESS';
export const ADD_ADDRESS_REQUEST_FAILURE = 'ADD_ADDRESS_REQUEST_FAILURE';
