export const GET_PAST_ORDER_DETAIL_REQUEST = 'GET_PAST_ORDER_DETAIL_REQUEST';
export const GET_PAST_ORDER_DETAIL_REQUEST_SUCCESS = 'GET_PAST_ORDER_DETAIL_REQUEST_SUCCESS';
export const GET_PAST_ORDER_DETAIL_REQUEST_FAILURE = 'GET_PAST_ORDER_DETAIL_REQUEST_FAILURE';
