export const GET_UPCOMING_ORDER_DETAIL_REQUEST = 'GET_UPCOMING_ORDER_DETAIL_REQUEST';
export const GET_UPCOMING_ORDER_DETAIL_REQUEST_SUCCESS = 'GET_UPCOMING_ORDER_DETAIL_REQUEST_SUCCESS';
export const GET_UPCOMING_ORDER_DETAIL_REQUEST_FAILURE = 'GET_UPCOMING_ORDER_DETAIL_REQUEST_FAILURE';

export const CANCEL_ORDER_REQUEST = "CANCEL_ORDER_REQUEST";
export const CANCEL_ORDER_REQUEST_SUCCESS = "CANCEL_ORDER_REQUEST_SUCCESS"
export const CANCEL_ORDER_REQUEST_FAILURE = "CANCEL_ORDER_REQUEST_FAILURE";