export const SUBMIT_EMAIL_OTP_REQUEST = 'SUBMIT_EMAIL_OTP_REQUEST';
export const SUBMIT_EMAIL_OTP_REQUEST_SUCCESS = 'SUBMIT_EMAIL_OTP_REQUEST_SUCCESS';
export const SUBMIT_EMAIL_OTP_REQUEST_FAILURE = 'SUBMIT_EMAIL_OTP_REQUEST_FAILURE';

export const RESEND_EMAIL_OTP_REQUEST = 'RESEND_EMAIL_OTP_REQUEST';
export const RESEND_EMAIL_OTP_REQUEST_SUCCESS = 'RESEND_EMAIL_OTP_REQUEST_SUCCESS';
export const RESEND_EMAIL_OTP_REQUEST_FAILURE = 'RESEND_EMAIL_OTP_REQUEST_FAILURE';