export const GET_PAST_ORDERS_REQUEST = 'GET_PAST_ORDERS_REQUEST';
export const GET_PAST_ORDERS_REQUEST_SUCCESS = 'GET_PAST_ORDERS_REQUEST_SUCCESS';
export const GET_PAST_ORDERS_REQUEST_FAILURE = 'GET_PAST_ORDERS_REQUEST_FAILURE';
